const experienceList = [
  {
    id: 1,
    user_id: 5,
    title: "Kamba",
    subtitle: "Environmental Specialist",
    start: "2012-05-02",
    end: "2020-05-16",
    responsibilities: "Business-focused object-oriented project",
  },
  {
    id: 2,
    user_id: 15,
    title: "Tagcat",
    subtitle: "Paralegal",
    start: "2018-03-22",
    end: "2020-11-03",
    responsibilities: "Horizontal neutral collaboration",
  },
  {
    id: 3,
    user_id: 13,
    title: "Quinu",
    subtitle: "Senior Cost Accountant",
    start: "2010-12-29",
    end: "2021-12-12",
    responsibilities: "Advanced needs-based initiative",
  },
  {
    id: 4,
    user_id: 14,
    title: "Dazzlesphere",
    subtitle: "VP Sales",
    start: "2015-10-13",
    end: "2020-10-11",
    responsibilities: "Public-key modular protocol",
  },
  {
    id: 5,
    user_id: 4,
    title: "Dazzlesphere",
    subtitle: "Chief Design Engineer",
    start: "2015-02-15",
    end: "2021-10-26",
    responsibilities: "Innovative neutral migration",
  },
  {
    id: 6,
    user_id: 13,
    title: "Linktype",
    subtitle: "Senior Sales Associate",
    start: "2017-08-14",
    end: "2022-06-30",
    responsibilities: "Multi-lateral transitional strategy",
  },
  {
    id: 7,
    user_id: 14,
    title: "Eidel",
    subtitle: "Electrical Engineer",
    start: "2014-10-12",
    end: "2019-10-03",
    responsibilities: "Cross-group static data-warehouse",
  },
  {
    id: 8,
    user_id: 2,
    title: "Zava",
    subtitle: "Human Resources Assistant III",
    start: "2016-04-15",
    end: "2021-05-22",
    responsibilities: "Business-focused hybrid structure",
  },
  {
    id: 9,
    user_id: 13,
    title: "Gabvine",
    subtitle: "Software Engineer I",
    start: "2010-09-02",
    end: "2021-08-12",
    responsibilities: "Integrated 24 hour contingency",
  },
  {
    id: 10,
    user_id: 8,
    title: "Aibox",
    subtitle: "Staff Accountant IV",
    start: "2011-02-22",
    end: "2020-02-13",
    responsibilities: "Team-oriented solution-oriented data-warehouse",
  },
  {
    id: 11,
    user_id: 18,
    title: "Skinte",
    subtitle: "Food Chemist",
    start: "2010-06-04",
    end: "2020-02-09",
    responsibilities: "Digitized analyzing architecture",
  },
  {
    id: 12,
    user_id: 23,
    title: "Rhybox",
    subtitle: "Marketing Manager",
    start: "2011-02-03",
    end: "2019-12-27",
    responsibilities: "Reactive local functionalities",
  },
  {
    id: 13,
    user_id: 6,
    title: "InnoZ",
    subtitle: "Analyst Programmer",
    start: "2017-09-10",
    end: "2020-04-23",
    responsibilities: "Up-sized value-added monitoring",
  },
  {
    id: 14,
    user_id: 3,
    title: "Nlounge",
    subtitle: "Information Systems Manager",
    start: "2017-10-29",
    end: "2022-01-15",
    responsibilities: "Multi-layered global extranet",
  },
  {
    id: 15,
    user_id: 23,
    title: "Realbuzz",
    subtitle: "Web Developer I",
    start: "2016-07-15",
    end: "2021-03-08",
    responsibilities: "Phased logistical encoding",
  },
  {
    id: 16,
    user_id: 8,
    title: "Linkbridge",
    subtitle: "Environmental Specialist",
    start: "2011-07-18",
    end: "2020-07-11",
    responsibilities: "Re-contextualized content-based protocol",
  },
  {
    id: 17,
    user_id: 14,
    title: "Pixonyx",
    subtitle: "General Manager",
    start: "2015-12-11",
    end: "2021-09-03",
    responsibilities: "Multi-tiered stable archive",
  },
  {
    id: 18,
    user_id: 19,
    title: "Yakidoo",
    subtitle: "Product Engineer",
    start: "2012-12-15",
    end: "2021-12-13",
    responsibilities: "Decentralized optimal orchestration",
  },
  {
    id: 19,
    user_id: 5,
    title: "Thoughtbridge",
    subtitle: "Sales Associate",
    start: "2015-08-16",
    end: "2020-07-01",
    responsibilities: "Ameliorated zero tolerance orchestration",
  },
  {
    id: 20,
    user_id: 17,
    title: "Mydo",
    subtitle: "Desktop Support Technician",
    start: "2013-09-21",
    end: "2022-04-13",
    responsibilities: "Organic global moderator",
  },
  {
    id: 21,
    user_id: 10,
    title: "Realblab",
    subtitle: "Recruiter",
    start: "2010-09-04",
    end: "2021-02-24",
    responsibilities: "Balanced stable groupware",
  },
  {
    id: 22,
    user_id: 20,
    title: "Edgetag",
    subtitle: "Software Engineer III",
    start: "2011-04-17",
    end: "2020-03-18",
    responsibilities: "Intuitive context-sensitive hub",
  },
  {
    id: 23,
    user_id: 14,
    title: "Kimia",
    subtitle: "Professor",
    start: "2015-10-23",
    end: "2020-02-07",
    responsibilities: "Multi-tiered composite frame",
  },
  {
    id: 24,
    user_id: 10,
    title: "Babblestorm",
    subtitle: "Systems Administrator I",
    start: "2014-09-04",
    end: "2020-05-27",
    responsibilities: "Robust asynchronous strategy",
  },
  {
    id: 25,
    user_id: 9,
    title: "Buzzdog",
    subtitle: "Mechanical Systems Engineer",
    start: "2017-02-06",
    end: "2020-04-08",
    responsibilities: "Digitized real-time pricing structure",
  },
  {
    id: 26,
    user_id: 6,
    title: "Photobean",
    subtitle: "Business Systems Development Analyst",
    start: "2015-11-16",
    end: "2020-03-05",
    responsibilities: "Quality-focused discrete firmware",
  },
  {
    id: 27,
    user_id: 15,
    title: "Skipfire",
    subtitle: "Analog Circuit Design manager",
    start: "2010-06-30",
    end: "2021-05-05",
    responsibilities: "Inverse systematic portal",
  },
  {
    id: 28,
    user_id: 10,
    title: "Skajo",
    subtitle: "Community Outreach Specialist",
    start: "2013-04-22",
    end: "2022-08-05",
    responsibilities: "Vision-oriented transitional standardization",
  },
  {
    id: 29,
    user_id: 13,
    title: "Wordpedia",
    subtitle: "VP Sales",
    start: "2010-12-13",
    end: "2019-12-14",
    responsibilities: "Stand-alone 4th generation instruction set",
  },
  {
    id: 30,
    user_id: 2,
    title: "Jazzy",
    subtitle: "Information Systems Manager",
    start: "2014-08-03",
    end: "2021-03-31",
    responsibilities: "Ameliorated 6th generation array",
  },
  {
    id: 31,
    user_id: 22,
    title: "Yoveo",
    subtitle: "Engineer II",
    start: "2014-12-06",
    end: "2021-06-24",
    responsibilities: "Reduced homogeneous circuit",
  },
  {
    id: 32,
    user_id: 12,
    title: "Meetz",
    subtitle: "Staff Scientist",
    start: "2014-08-03",
    end: "2021-11-12",
    responsibilities: "Self-enabling tertiary collaboration",
  },
  {
    id: 33,
    user_id: 13,
    title: "Babblestorm",
    subtitle: "Research Assistant II",
    start: "2014-09-18",
    end: "2019-09-18",
    responsibilities: "Optional directional standardization",
  },
  {
    id: 34,
    user_id: 25,
    title: "Kare",
    subtitle: "Occupational Therapist",
    start: "2011-05-08",
    end: "2021-10-25",
    responsibilities: "Advanced global knowledge user",
  },
  {
    id: 35,
    user_id: 4,
    title: "Skibox",
    subtitle: "Health Coach IV",
    start: "2016-01-28",
    end: "2021-12-11",
    responsibilities: "Configurable bandwidth-monitored interface",
  },
  {
    id: 36,
    user_id: 5,
    title: "Yodo",
    subtitle: "Junior Executive",
    start: "2016-12-15",
    end: "2022-02-01",
    responsibilities: "Robust explicit access",
  },
  {
    id: 37,
    user_id: 13,
    title: "Yodoo",
    subtitle: "Desktop Support Technician",
    start: "2016-04-27",
    end: "2022-01-04",
    responsibilities: "Compatible full-range database",
  },
  {
    id: 38,
    user_id: 13,
    title: "Agivu",
    subtitle: "VP Sales",
    start: "2012-11-09",
    end: "2021-10-23",
    responsibilities: "Seamless bandwidth-monitored ability",
  },
  {
    id: 39,
    user_id: 10,
    title: "Fivechat",
    subtitle: "Systems Administrator IV",
    start: "2012-01-10",
    end: "2021-03-10",
    responsibilities: "Networked fresh-thinking website",
  },
  {
    id: 40,
    user_id: 22,
    title: "Bubblebox",
    subtitle: "Nurse",
    start: "2013-04-11",
    end: "2021-05-31",
    responsibilities: "Enterprise-wide responsive focus group",
  },
  {
    id: 41,
    user_id: 2,
    title: "Brightdog",
    subtitle: "Senior Financial Analyst",
    start: "2018-09-01",
    end: "2020-10-30",
    responsibilities: "Integrated 6th generation superstructure",
  },
  {
    id: 42,
    user_id: 16,
    title: "Avaveo",
    subtitle: "VP Marketing",
    start: "2018-03-07",
    end: "2021-07-29",
    responsibilities: "Fundamental multi-state complexity",
  },
  {
    id: 43,
    user_id: 25,
    title: "BlogXS",
    subtitle: "Engineer IV",
    start: "2017-06-13",
    end: "2021-08-07",
    responsibilities: "Versatile logistical strategy",
  },
  {
    id: 44,
    user_id: 18,
    title: "Browsecat",
    subtitle: "Automation Specialist IV",
    start: "2013-03-17",
    end: "2019-10-24",
    responsibilities: "Vision-oriented 3rd generation middleware",
  },
  {
    id: 45,
    user_id: 5,
    title: "Eabox",
    subtitle: "Software Consultant",
    start: "2010-02-10",
    end: "2020-03-16",
    responsibilities: "Open-architected mission-critical flexibility",
  },
  {
    id: 46,
    user_id: 2,
    title: "Eadel",
    subtitle: "Design Engineer",
    start: "2010-04-02",
    end: "2021-06-18",
    responsibilities: "Multi-channelled user-facing analyzer",
  },
  {
    id: 47,
    user_id: 12,
    title: "Eazzy",
    subtitle: "Senior Editor",
    start: "2017-04-03",
    end: "2020-05-16",
    responsibilities: "Advanced zero tolerance concept",
  },
  {
    id: 48,
    user_id: 3,
    title: "Oyonder",
    subtitle: "GIS Technical Architect",
    start: "2017-01-23",
    end: "2021-10-19",
    responsibilities: "Centralized client-server circuit",
  },
  {
    id: 49,
    user_id: 13,
    title: "Zoozzy",
    subtitle: "Structural Analysis Engineer",
    start: "2012-09-25",
    end: "2020-02-01",
    responsibilities: "Total methodical application",
  },
  {
    id: 50,
    user_id: 5,
    title: "Voonix",
    subtitle: "Internal Auditor",
    start: "2017-01-09",
    end: "2021-04-09",
    responsibilities: "Cross-platform system-worthy structure",
  },
];

export async function getExperienceListForUserId(userId) {
  const list = experienceList.filter((item) => item.user_id == userId);
  return [...list];
}

export async function getExperience(experienceId) {
  const experience = experienceList.find((e) => e.id == experienceId);
  if (experience) return { ...experience };
}

export async function saveExperience(experience) {
  if (experience.id) {
    const e = experienceList.find((item) => item.id === experience.id);
    e.title = experience.title;
    e.subtitle = experience.subtitle;
    e.start = experience.start;
    e.end = experience.end;
    e.responsibilities = experience.responsibilities;
    return e;
  } else {
    const newExperience = { ...experience };
    newExperience.id = experienceList.length + 1;
    experienceList.push(newExperience);
    return newExperience;
  }
}

export async function deleteExperience(experienceId) {
  const index = experienceList.indexOf(
    experienceList.find((e) => e.id == experienceId)
  );
  if (index > -1) {
    experienceList.splice(index, 1);
  }
}

export default {
  getExperienceListForUserId,
  getExperience,
  saveExperience,
  deleteExperience,
};
